### ISSUE TITLE
v1 milestone tasks

### ISSUE THREAD

**Issue by GochoMugo** [GochoMugo/cli-output#4]
- [x] update dependencies
- [x] update copyright license year
- [x] add changelog
- [x] fix issues tagged `v1`
- [x] test against Node v4.2.x

**Comment by GochoMugo** [comment]
**DONE &mdash; v1.0.0**
